// scripts/render/html.ts
import type { ReportData } from '../compute/types.js';

export function renderHtml(r: ReportData): string {
  const fmt = (n: number | null, opts?: { currency?: boolean; pct?: boolean }): string => {
    if (n === null || n === undefined) return '—';
    if (opts?.pct) return n > 1 ? '—' : (n * 100).toFixed(1) + '%';
    if (opts?.currency) return '$' + n.toLocaleString(undefined, { maximumFractionDigits: 0 });
    return n.toLocaleString();
  };

  const staleBanner = r.stale
    ? `<div class="banner banner-stale"><div class="container"><strong>Stale</strong> — last refresh failed ${r.stale_reason ?? ''}</div></div>`
    : '';

  return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>CPG Affiliate — Lead Funnel</title>
  <link rel="stylesheet" href="assets/styles.css">
</head>
<body>
${staleBanner}
<section class="band-dark">
  <div class="container">
    <span class="section-num">CPG Affiliate</span>
    <h1>Lead Funnel Report</h1>
    <p class="lede">Window: ${r.window.start} → ${r.window.end} · Generated ${r.generated_at.slice(0, 10)}</p>
  </div>
</section>

${renderKpiBar(r, fmt)}
${renderBySource(r, fmt)}
${renderMql(r, fmt)}
${renderSql(r, fmt)}
${renderDefinitions()}

<footer><div class="container">Generated by <code>cpg-status</code> · ${r.generated_at}</div></footer>

<script id="report-data" type="application/json">${JSON.stringify(r)}</script>
<script src="https://cdn.jsdelivr.net/npm/chart.js@4.4.0/dist/chart.umd.min.js"></script>
<script src="assets/charts.js"></script>
</body>
</html>`;
}

function renderKpiBar(r: ReportData, fmt: (n: number | null, opts?: { currency?: boolean; pct?: boolean }) => string): string {
  const k = r.kpis;
  return `<section><div class="container">
    <span class="section-num">02 · Headline</span>
    <h2>Current month at a glance</h2>
    <div class="metric-grid">
      <div class="stat"><div class="stat-num">${fmt(k.total_leads)}</div><div class="stat-label">Total Leads</div></div>
      <div class="stat"><div class="stat-num">${fmt(k.mql)}</div><div class="stat-label">MQL</div></div>
      <div class="stat"><div class="stat-num">${fmt(k.sql)}</div><div class="stat-label">SQL</div></div>
      <div class="stat"><div class="stat-num">${fmt(k.closed_won)}</div><div class="stat-label">Closed Won</div></div>
    </div>
  </div></section>`;
}

function renderMonthlyTable(r: ReportData, fmt: (n: number | null, opts?: { currency?: boolean; pct?: boolean }) => string): string {
  const rows = r.monthly.map((m) => `
    <tr>
      <td>${m.month}</td>
      <td>${fmt(m.spend_by_source.gads_lp, { currency: true })}</td>
      <td>${fmt(m.spend_by_source.bison_cold, { currency: true })}</td>
      <td>${fmt(m.spend_total, { currency: true })}</td>
      <td>${fmt(m.total_leads)}</td>
      <td>${fmt(m.cpl, { currency: true })}</td>
    </tr>`).join('');
  return `<section><div class="container">
    <span class="section-num">03 · Spend & CPL</span>
    <h2>Spend, leads, cost per lead</h2>
    <table>
      <thead><tr><th>Month</th><th>Spend (gads)</th><th>Spend (bison)</th><th>Total Spend</th><th>Leads</th><th>CPL</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
  </div></section>`;
}

function renderBySource(r: ReportData, fmt: (n: number | null, opts?: { currency?: boolean; pct?: boolean }) => string): string {
  const rows = r.monthly.map((m) => `
    <tr>
      <td>${m.month}</td>
      <td>${fmt(m.leads_by_source.gads_lp)}</td>
      <td>${fmt(m.leads_by_source.bison_cold)}</td>
      <td>${fmt(m.total_leads)}</td>
    </tr>`).join('');
  return `<section><div class="container">
    <span class="section-num">04 · Source mix</span>
    <h2>Inbound leads by source</h2>
    <div class="card"><canvas id="chart-by-source" height="340"></canvas></div>
    <table style="margin-top: 24px;">
      <thead><tr><th>Month</th><th>gads_lp</th><th>bison_cold</th><th>Total</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
  </div></section>`;
}

function renderMql(r: ReportData, fmt: (n: number | null, opts?: { currency?: boolean; pct?: boolean }) => string): string {
  const rows = r.monthly.map((m) => `
    <tr>
      <td>${m.month}</td>
      <td>${fmt(m.mql_by_source.gads_lp)}</td>
      <td>${fmt(m.mql_by_source.bison_cold)}</td>
      <td>${fmt(m.mql_rate, { pct: true })}</td>
    </tr>`).join('');
  return `<section><div class="container">
    <span class="section-num">05 · MQL</span>
    <h2>Marketing-qualified leads (Booked Call)</h2>
    <div class="grid-2">
      <div class="card"><canvas id="chart-funnel" height="180"></canvas></div>
      <div class="card"><canvas id="chart-mql-by-source" height="180"></canvas></div>
    </div>
    <table style="margin-top: 24px;">
      <thead><tr><th>Month</th><th>MQL (gads)</th><th>MQL (bison)</th><th>MQL Rate</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
  </div></section>`;
}

function renderSql(r: ReportData, fmt: (n: number | null, opts?: { currency?: boolean; pct?: boolean }) => string): string {
  const rows = r.monthly.map((m) => `
    <tr>
      <td>${m.month}</td>
      <td>${fmt(m.sql_stage_split.proposal_sent)}</td>
      <td>${fmt(m.sql_stage_split.negotiating)}</td>
      <td>${fmt(m.sql_stage_split.closed_won)}</td>
      <td>${fmt(m.sql_rate, { pct: true })}</td>
    </tr>`).join('');
  return `<section><div class="container">
    <span class="section-num">06 · SQL</span>
    <h2>Sales-qualified deals (Proposal Sent · Negotiating · Closed Won)</h2>
    <div class="grid-2">
      <div class="card"><canvas id="chart-sql-donut" height="180"></canvas></div>
      <div class="card">
        <h3>Current month split</h3>
        <p><span class="tag">Proposal Sent</span> ${r.sql_stage_split.proposal_sent}</p>
        <p><span class="tag tag-blue">Negotiating</span> ${r.sql_stage_split.negotiating}</p>
        <p><span class="tag tag-green">Closed Won</span> ${r.sql_stage_split.closed_won}</p>
      </div>
    </div>
    <table style="margin-top: 24px;">
      <thead><tr><th>Month</th><th>Proposal Sent</th><th>Negotiating</th><th>Closed Won</th><th>SQL Rate</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
  </div></section>`;
}

function renderCohort(r: ReportData, fmt: (n: number | null, opts?: { currency?: boolean; pct?: boolean }) => string): string {
  const allInsufficient = r.cohort_cpa.every((c) => c.insufficient_data);
  const inner = allInsufficient
    ? `<div class="callout callout-info"><strong>Insufficient data</strong> — N+90 cohort CPA requires 90 days post-launch. Launch: ${r.launch_date}. Available: ${r.cohort_cpa.length > 0 ? r.cohort_cpa[r.cohort_cpa.length - 1].cohort_month : '—'}.</div>`
    : `<table><thead><tr><th>Cohort</th><th>Spend (N−3)</th><th>Wins</th><th>CPA</th></tr></thead><tbody>${r.cohort_cpa.map((c) => `
      <tr><td>${c.cohort_month}</td><td>${fmt(c.spend_n_minus_3, { currency: true })}</td><td>${fmt(c.wins)}</td><td>${c.insufficient_data ? '<span class="tag tag-outline">pending</span>' : fmt(c.cpa, { currency: true })}</td></tr>`).join('')}</tbody></table>`;
  return `<section><div class="container">
    <span class="section-num">07 · Cohort CPA</span>
    <h2>Deals closed — N+90 cohort</h2>
    ${inner}
  </div></section>`;
}

function renderCpaPayback(r: ReportData, fmt: (n: number | null, opts?: { currency?: boolean; pct?: boolean }) => string): string {
  void fmt;
  return `<section><div class="container">
    <span class="section-num">08 · CPA & Payback</span>
    <h2>CPA by source + payback</h2>
    <div class="card"><canvas id="chart-cohort-line" height="100"></canvas></div>
    <p style="margin-top: 16px;">Payback calculation requires gross-margin input from the client. Awaiting target.</p>
  </div></section>`;
}

function renderLeadLog(r: ReportData): string {
  const rows = r.lead_log.slice(0, 50).map((l) => `
    <tr>
      <td><span class="signal-time">${l.created_at.slice(0, 10)}</span></td>
      <td><code>${l.email_hash}</code></td>
      <td>${l.source}</td>
      <td>${l.is_mql ? '<span class="tag tag-green">MQL</span>' : '<span class="tag tag-outline">—</span>'}</td>
      <td>${l.is_sql ? '<span class="tag tag-blue">SQL</span>' : '<span class="tag tag-outline">—</span>'}</td>
      <td>${l.current_stage}</td>
    </tr>`).join('') || '<tr><td colspan="6" style="text-align: center; color: #999;">No leads in window</td></tr>';
  return `<section><div class="container">
    <span class="section-num">09 · Lead log</span>
    <h2>Recent leads (last 50)</h2>
    <table>
      <thead><tr><th>Created</th><th>Email</th><th>Source</th><th>MQL?</th><th>SQL?</th><th>Stage</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>
  </div></section>`;
}

function renderDefinitions(): string {
  return `<section><div class="container">
    <span class="section-num">10 · Definitions</span>
    <h2>How these metrics are defined</h2>
    <div class="grid-2">
      <div class="card"><h4>MQL</h4><p>Lead has reached Attio Leads stage <code>Booked Call</code>. CPG-specific override of the SOP-generic Fit+Intent ≥ 60.</p></div>
      <div class="card"><h4>SQL</h4><p>Deal has reached <code>Proposal Sent</code>, <code>Negotiating</code>, or <code>Closed Won</code>. CPG-specific override of the SOP-generic BANT-lite.</p></div>
    </div>
    <p style="margin-top: 16px; font-size: 0.85em; color: var(--muted);">Funnel counts in-scope channels only — Google Ads (<code>gads_lp</code>) and bison cold email (<code>bison_cold</code>). Contacts from other sources are excluded.</p>
    <p style="margin-top: 24px; font-size: 0.85em; color: var(--muted);">Full rubric: <code>kamg-ops/clients/cpg-affiliate/metrics-rubric.md</code></p>
  </div></section>`;
}
